#!/usr/bin/env python3
# top5_fpga_efficiency.py
#
#   ▸ Reads ppa_master.csv
#   ▸ Calculates PPA metrics **per (env, benchmark)**
#   ▸ Prints **Top‑K benchmarks for each env** (composite rank)
#   ▸ Optionally dumps the concatenated ranked table to CSV
#
#   Usage:  python top5_fpga_efficiency.py  ppa_master.csv  [-k 5] [-o out.csv]
#   Author:  <your name>, 2025
# ---------------------------------------------------------------------------

import argparse
from pathlib import Path

import pandas as pd


def build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Rank FPGA off‑load benchmarks per environment by "
                    "speed‑up, resource utilisation and power.")
    p.add_argument("csv", help="ppa_master.csv generated by the pre‑processor")
    p.add_argument("-k", "--topk", type=int, default=5,
                   help="How many benchmarks to list per environment (default=5)")
    p.add_argument("-o", "--out", type=Path,
                   help="Optional path to write a single ranked CSV")
    return p


def main() -> None:
    args = build_argparser().parse_args()
    df = pd.read_csv(args.csv)

    # -------- sanity checks -------------------------------------------------
    if "env" not in df.columns:
        raise SystemExit("ERROR: csv must contain an 'env' column")
    # -----------------------------------------------------------------------

    # -------- metric aggregation -------------------------------------------
    g = (df.groupby(["env", "benchmark"], as_index=False)
           .agg(avg_saved_ns=("saved_cpu_ns",   "mean"),
                avg_delta_cyc=("delta_cycles",   "mean"),  # <-- optional
                avg_clb_pct=("clb_pct_board",   "mean"),
                avg_dsp_pct=("dsp_pct_board",   "mean"),
                avg_dyn_w=("dyn_W",             "mean"),
                avg_area_mm2=("area_mm2",       "mean")))

    g["cost_pct"] = g["avg_clb_pct"] + g["avg_dsp_pct"]
    g = g[g["cost_pct"] > 0]                         # avoid div/0

    g["ppc_time"]   = g["avg_saved_ns"]  / g["cost_pct"]
    g["ppc_time_w"] = g["avg_saved_ns"]  / (g["cost_pct"] * g["avg_dyn_w"])

    # -------- per‑environment ranking --------------------------------------
    ranked_frames = []
    for env, sub in g.groupby("env"):
        sub = sub.copy()

        # composite rank (lower is better)
        sub["r_perf"]   = sub["avg_saved_ns"].rank(ascending=False, method="min")
        sub["r_cost"]   = sub["cost_pct"].rank(ascending=True,  method="min")
        sub["r_power"]  = sub["avg_dyn_w"].rank(ascending=True,  method="min")
        sub["r_area"]   = sub["avg_area_mm2"].rank(ascending=True, method="min")
        sub["rank_cmp"] = sub[["r_perf", "r_cost", "r_power", "r_area"]].mean(axis=1)

        sub = sub.sort_values("rank_cmp").head(args.topk)
        ranked_frames.append(sub)

        print(f"\n=== {env} — Top‑{args.topk} ===")
        cols = ["benchmark", "avg_saved_ns", "avg_clb_pct", "avg_dsp_pct",
                "avg_dyn_w", "ppc_time", "ppc_time_w"]
        try:
            print(sub[cols].round(3).to_markdown(index=False))
        except ImportError:
            # fall back if tabulate is missing
            print(sub[cols].round(3).to_string(index=False))

    # -------- optional CSV dump --------------------------------------------
    if args.out:
        pd.concat(ranked_frames, ignore_index=True).to_csv(args.out, index=False)
        print(f"\n[✓] Ranked table written to: {args.out}")


if __name__ == "__main__":
    main()
